let strOne = "HelloLadies";
console.log(strOne[2], strOne[6]);
let name = "arezoo";
let age = 30;
let year = 2020;
let isMarried = true;
let programmingLangueage = "javaScript";
let isFun = true;
console.log(name + " is " + age + " in " + year);
console.log(name + " is married: " + isMarried);
console.log(programmingLangueage + " is Fun: " + isFun);
console.log(programmingLangueage[0], programmingLangueage[4]);
console.log(programmingLangueage.length);
